### PR TITLE
[#161886901] forward 429 and 409 errors

### PR DESCRIPTION
**Pull request by gunzip**

### CODE REVIEW

**Comment by digitalcitizenship** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  Please include a Pivotal story at the beginning of the PR title (see below).
  </td>
    </tr>
  
<tr>
      <td>:warning:</td>
      <td>

  Please include a description of your PR changes.
  </td>
    </tr>
  </tbody>
</table>



  Example of PR titles that include pivotal stories:

  * single story: `[#123456] my PR title`
  * multiple stories: `[#123456,#123457,#123458] my PR title`

    
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by gunzip** [comment]
@cloudify can we merge this one ?

**Comment by cloudify** [comment]
@gunzip I think we're still missing:

- [ ] returning the 429 status to the app
- [ ] exposing the 429 status to the proxy specs (that the app uses to generate the client)

**Comment by cloudify** [comment]
Superseded by #421 421

**Pull request closed without merging**
