### PR TITLE
[#169836230] Add required APNS headers to send notification

### PR DESCRIPTION
**Pull request by BurnedMarshal**

### CODE REVIEW

**Comment by digitalcitizenship** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  Please include a description of your PR changes.
  </td>
    </tr>
  </tbody>
</table>



## Affected stories

  * 🌟 [#169836230](https://www.pivotaltracker.com/story/show/169836230): Aggiungere l'header alle push notifications

<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by gunzip** [comment]
lgtm if we use token-based authentication. do we ? cc @fpersico

**Comment by BurnedMarshal** [comment]
> lgtm if we use token-based authentication. do we ? cc @fpersico

@gunzip Do you mean to send a notification to azure? We create a NotificationHubService and the connection string is provided throw an ENV variable
```
const notificationHubService = azure.createNotificationHubService(
        this.hubName,
        this.endpointOrConnectionString
      );
notificationHubService.send(....
```

**Comment by francescopersico** [comment]
> lgtm if we use token-based authentication. do we ? cc @fpersico

Yes we use token based auth for both old and new infrastructure.

**Pull request merged**
