### PR TITLE
[#164725697] Add Lepida ID

### PR DESCRIPTION
**Pull request by fpersico**
I have not tested it but i think is safe to merge.

### CODE REVIEW

**Comment by cloudify** [comment]
Just for reference, where did you get the metadata?

**Comment by digitalcitizenship** [comment]
## Affected stories

  * 🌟 [#164725697](https://www.pivotaltracker.com/story/show/164725697): Come CIT voglio trovare fra gli identity provider SPID anche LepidaID

<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by fpersico** [comment]
https://registry.spid.gov.it/identity-providers

**Comment by fpersico** [comment]
Also available here https://www.agid.gov.it/it/piattaforme/spid/identity-provider-accreditati

**Pull request merged**
